#! /usr/bin/env bash

set -e

source script/env "$@"

cargo fmt --all -- --check
cargo clippy --all-targets --all-features -- -D warnings
cargo verify-project
cargo doc --no-deps --document-private-items --all-features --workspace
