#! /usr/bin/env bash

set -euo pipefail

source script/env "$@"

ensure_rust_toolchain

FMT_FLAGS=(-- --check)
case "${1:-}" in
  --A|-A|-a|--a|--auto-fix)
    FMT_FLAGS=()
    ;;
esac

cargo fmt --all "${FMT_FLAGS[@]}"
cargo clippy --frozen --all-targets --all-features -- -D warnings
cargo verify-project
cargo doc --frozen --no-deps --document-private-items --all-features --workspace
